// Generated by CoffeeScript 1.3.3
(function() {
  var cleanup, cleanupInterval, exec, fs, jsdom, storiesRunning, updateStory;

  jsdom = require('jsdom');

  fs = require('fs');

  exec = require('child_process').exec;

  storiesRunning = 0;

  updateStory = function(fullURL, fileName) {
    return jsdom.env(fullURL, function(err, window) {
      var entryContent, story;
      entryContent = window.document.getElementsByClassName('entry-content')[0];
      if (entryContent) {
        story = entryContent.textContent.replace(/\t/g, '');
        return fs.writeFile('./stories/' + fileName, story, function(err) {
          storiesRunning--;
          if (err) {
            return console.log(err);
          } else {
            return console.log(fileName, 'saved.');
          }
        });
      } else {
        storiesRunning--;
        return console.log(fullURL, 'has no .entry-content');
      }
    });
  };

  cleanup = function() {
    var child;
    if (storiesRunning === 0) {
      clearInterval(cleanupInterval);
      console.log('time to rumble');
      child = exec('git add . && git commit -a -m "differ" && git push origin master', function(error, stdout, stderr) {
        console.log(stdout);
        if (error) {
          return console.log('error', error);
        }
      });
    } else {
      console.log(storiesRunning + ' left.');
    }
  };

  cleanupInterval = setInterval(cleanup, 2000);

  jsdom.env('http://www.dailyemerald.com', function(err, window) {
    var fileName, fullURL, url, _i, _len, _ref, _results;
    _ref = window.document.getElementsByTagName('a');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      url = _ref[_i];
      if (url.href.indexOf('dailyemerald.com') !== -1) {
        fullURL = url.href;
        fileName = url.href.split('.com')[1].replace(/\//g, '_');
        updateStory(fullURL, fileName);
        _results.push(storiesRunning++);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

}).call(this);
